---
title: "Constructing"
output: 
  html_document:
    df_print: paged
---

This is where I present some of the R-projects that I'm currently working on.


## Applied Financial Econometrics

* [Applied Financial Econometrics HW1](content/Applied_Financial_Econometrics_HW1.pdf)


## Bayesian Statistics

Bayesian Statistics course taught by Jingchen (Monika) Hu. The lecture is highly recommended!! 

I added some comments in the slides.

* [Lec 1 Introduction annotated](content/Bayesian_Statistics/F19MATH347_Intro_annotated.pdf)
* [All nighters example](content/Bayesian_Statistics/All_nighters_example.pdf)
* [HW1](content/Bayesian_Statistics/Bayesian_Statistics_HW1.pdf)
* [Lec 2 Proportion annotated](content/Bayesian_Statistics/F19MATH347_Proportion_annotated.pdf)
* [Tokyo Express dining preference example](content/Bayesian_Statistics/F19MATH347_Proportion_R.pdf)
* [HW2](content/Bayesian_Statistics/HW2.pdf)
* [Lab1](content/Bayesian_Statistics/Lab1_Jay.pdf)
* [Lec 3 Mean annotated](content/Bayesian_Statistics/F19MATH347_Mean_annotated.pdf)
* [Lec 3 derivation notes](content/Bayesian_Statistics/F19MATH347_Mean_notes.pdf)
* [Lec 3 derivation exercises](content/Bayesian_Statistics/F19MATH347 Gamma Poisson Conjugate.pdf)
* [Solutions to Lec 3 derivation exercises](content/Bayesian_Statistics/Solutions_to_Gamma_Poisson.pdf)
* [Lec 3 MonteCarlo annotated](content/Bayesian_Statistics/F19MATH347_MonteCarlo_annotated.pdf)
* [Lec 3 R example](content/Bayesian_Statistics/F19MATH347_Mean_R.pdf)

## Financial Crisis

* [Financial Crisis HW1](content/Financial_Crisis/Financial_Crisis_HW1.pdf)
* [Financial Crisis HW2](content/Financial_Crisis/Financial_Crisis_HW2.pdf)
* [Financial Crisis HW3](content/Financial_Crisis/Financial_Crisis_HW3.pdf)
* [Financial Crisis HW4](content/Financial_Crisis/Financial_Crisis_HW4.pdf)
* [Financial Crisis HW5](content/Financial_Crisis/Financial_Crisis_HW5.pdf)
* [Financial Crisis HW6](content/Financial_Crisis/Financial_Crisis_HW6.pdf)
* [Financial Crisis HW7](content/Financial_Crisis/Financial_Crisis_HW7.pdf)

## Labor Economics

This project is a paper proposal for the course Labor Economics when I was in National Chengchi University.

The software I used was STATA. I will probably use R next time. HA! 

* [Labor Economics Project](content/107205036.pdf)


## Statistical Computing

* [Statistical Computing](https://shang-chieh0830.github.io/Statistical_Computing/)


