---
title: "Shang-Chieh's webpage"
output: html_document
date: "Last updated: `r Sys.Date()`"
---

Welcome to my webpage. I'm Shang-Chieh Wei. I'm currently a graduate student in the Department of Economics at National Taiwan University. You can download my CV [here](content/Resume.pdf).

## Education

- __M.A.__ in Economics

  September 2022 - Present, __National Taiwan University__, Taiwan 
  
  Thesis Topic: [_Analyzing the Impact of Policies and Macroeconomic Factors on Electric Vehicle Sales_](content/EV_Slides.pdf)
  

- __B.A.__ in Economics (with a Minor in Public Finance)
  
  September 2018 - June 2022, __National Chengchi University__, Taiwan

## Scholarships, Awards and Honors

- [__Honorary membership of The Phi Tau Phi Scholastic Honor Society__](http://www.phitauphi.org.tw) of the Republic of China, 2022

  A certificate that warrants students who have achieved academic excellence upon graduation to be selected as honorary members of the Society by National Chengchi University.
  
  Every domestic university may recommend up to 1% of undergraduate graduands that are excellent in academic performance as well as moral conduct to receive the honorary membership of the Society. The recommendation criteria are subject to the average of semester grades prior to the semester of graduation.
  
- [__The Memorial Scholarship Foundation to Lin Hsiung Chen__](http://www.ta-yung.com.tw/?fbclid=IwAR0I4QUFx46Rl6HGlP9VK09xOIrpQt5RWZbKc00NhUSNYJ-OjkWh_lnJv9I), 2021

  This scholarship is designed to reward outstanding students from public and private universities, as well as independent colleges in Taiwan. There are only 50 scholarships available nationwide. Applicants must have achieved an overall average score of 85 or above in their academic performance for the previous academic year.
  
- __Outstanding Student Scholarship__, College of Social Sciences, NCCU, 2020 Spring, 2021 Fall

  From the second semester of the first year to the first semester of the fourth year, having completed at least 12 credits in the preceding semester.

  Attaining a ranking within the top ten percent (unconditionally rounded up) of students in each department and class within the undergraduate division, based on the previous semester's academic performance.

  Achieving a passing grade or higher in all courses and having no records of course withdrawal or disciplinary actions in the preceding semester.
  
- __Professor Liu, Xing-Hua Memorial Scholarship__, Department of Public Finance, NCCU, Spring 2020

  This scholarship is awarded to the student with the highest academic performance in the field of economics.
  
- __Academic Excellence Awards__, NCCU, Fall 2018, Spring 2019, Fall 2019, Spring 2020, Fall 2020, Spring 2021, Fall 2021

  Students  who  rank  in  the  top  5%  (rounded  up  unconditionally)  in  their  department and year in a semester shall be given a scholarship and a certificate.

## Teaching Experience

- Teaching Assistant at NTU:

  [Principle of Microeconomics (ECON1022)](https://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=303%2010130&class=03&dpt_code=7050&ser_no=39785&semester=112-1&lang=EN), Fall 2023

- Grader at NTU:

  [Market and Strategy (ECON 5126)](https://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=323%20U2250&class=&dpt_code=3230&ser_no=82701&semester=111-2&lang=EN), Spring 2023

  [Managerial Economics (ECON 5147)](https://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=323%20U5400&class=&dpt_code=3030&ser_no=86258&semester=111-2&lang=EN), Spring 2023
  
  [Introduction to Law Economics (ECON 5058)](https://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=323%20U7170&class=&dpt_code=3230&ser_no=28669&semester=111-1&lang=EN), Fall 2022

## Languages

- English (Fluent)

  TOEFL: 108/120, September 2020

- Chinese (Native)

## Programming Skills

R, Stata, and $\LaTeX$


## Coursework

- [Vanilla web scraping on Booking.com](https://youtu.be/tecRUg1QDRk)

- [A Summary of Probability Distributions](content/course_work/Summary.html)

- Stock Return Differentials as Predictors of Daily Exchange Rate Movements

- The Effect of Food Delivery Platform on the Wage Difference after Job Status Changing

## Courses

- Math and Stat

  Calculus (A+/A+), Statistics (A+/A+), Linear Algebra (A+/A-), Applications of Differential Equation (A+), Advanced Calculus (A+/A), Mathematical Statistics (A+/A+), Multivariate Analysis (A+), Theory of Statistics (Ⅰ) (A+), Data Science and Social Inquiry (A+)
  
- Econ and Finance

  Economics (A+/A+), Microeconomics (A+/A+), Macroeconomics (A+/A+), Public Finance (A+/A+), Money and Banking (A+/A+), Financial Management (A+), International Finance (A+), Labor Economics (A+), Industrial Economics (A+), Econometrics (I)/(II) (A+/A+), Business Analytics with SAS/R (A+), Introduction to Numerical Methods in Economics and Econometrics (A+), Applied Financial Econometrics (A+)


