---
title: "Resources"
output: 
  html_document:
    df_print: paged
---

There are many useful resources online. Most of them are free and public!!

I will put some links connected to some of these online resources that I found particularly useful. Check them out to see whether they also meet your needs.


## Bayesian Statistics

* [An Introduction to Bayesian Thinking](https://statswithr.github.io/book/)
* [Bayes Rules! An Introduction to Applied Bayesian Modeling](https://www.bayesrulesbook.com)
* [Bayesian Data Analysis course](https://avehtari.github.io/BDA_course_Aalto/gsu2023.html)
* [Probability and Bayesian Modeling](https://monika76five.github.io/ProbBayes/)


## Finance

* [Technical Analysis with R](https://bookdown.org/kochiuyu/technical-analysis-with-r-second-edition2/)
* [Computational Finance](https://bookdown.org/compfinezbook/introcompfinr/)
* [Financial Analytics](https://bookdown.org/wfoote01/faur/)
* [Tidy Finance with R](https://www.tidy-finance.org)

## Math 

* [LibreTexts Analysis](https://math.libretexts.org/Bookshelves/Analysis)

## Statistics 

* [LibreTexts Statistics](https://stats.libretexts.org)
* [StatLect](https://www.statlect.com/glossary/)
* [Statistics Online](https://online.stat.psu.edu/statprogram/)

## Statistical/Machine Learning

* [ISLR](https://www.statlearning.com)
* [Basics of Statistical Learning](https://statisticallearning.org)

* [Machine Learning(MATH3431)](https://bookdown.org/hailiangdu80/Machine_Learning_and_Neural_Networks/)
* [Machine Learning I(MATH42815)](https://bookdown.org/ssjackson300/Machine-Learning-Lecture-Notes/)
* [Machine Learning II(MATH42815)](https://bookdown.org/hailiangdu/Lecture_notes/)
* [STA 430](http://campus.murraystate.edu/academic/faculty/cmecklin/STA430/_book/)
* [Hands on Machine Learning](https://bradleyboehmke.github.io/HOML/)
* [Applied Machine Learning](https://dionysus.psych.wisc.edu/iaml/)

## Time Series 

* [ATSA](https://atsa-es.github.io/atsa/index.html)
* [Forecasting and Analytics with ADAM](https://openforecast.org/adam/)
* [Forecasting: Principles and Practice](https://otexts.com/fpp3/)
* [Time Series: A Data Analysis Approach (S&S)](https://www.stat.pitt.edu/stoffer/tsda/)
* [Time Series Analysis and it's applications with examples in R](https://www.stat.pitt.edu/stoffer/tsa4/)







